#!/bin/sh
set -e

local_repo="/dump"
backup_name="$(date)"
mongo_url="${MONGO_URL}"
project_name="${PROJECT_NAME}"

if [ -z "${mongo_url}" ]; then
  echo "MONGO_URL is not set"
  exit 2
fi

if [ -z "${project_name}" ]; then
  project_name="dump"
fi

echo "Backup: ${backup_name}"

cd "${local_repo}"
git reset --hard
rm -rf *

# Perform the actual dump
mongodump --uri "${mongo_url}" --out "${project_name}"

if [ -z "$(git status -s)" ]; then
  echo "Nothing to Commit"
  exit 1
fi

echo "Staging files list"
git add -A

echo "Pushing"
git commit -m "${backup_name}"
git push origin master
