#!/bin/sh

backup_cycle_interval="${BACKUP_CYCLE_INTERVAL}"

if [ -z "${backup_cycle_interval}" ]; then
  echo "BACKUP_CYCLE_INTERVAL is not set"
  exit 2
fi

while true; do
  echo "\n\n"
  run-backup-cycle
  sleep "${backup_cycle_interval}"
done
