name: Build & Push to DockerHub

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.0.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ksdme/git-mongo-backup
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
